#apiVersion: v1
#kind: Service
#metadata:
#  name: {{ include "helloworldapichart.fullname" . }}
#  labels:
#    {{- include "helloworldapichart.labels" . | nindent 4 }}
#spec:
#  type: {{ .Values.service.type }}
#  ports:
#    - port: {{ .Values.service.port }}
#      targetPort: http
#      protocol: TCP
#      name: http
#  selector:
#    {{- include "helloworldapichart.selectorLabels" . | nindent 4 }}
