apiVersion: "v1"
kind: "Service"
metadata:
  name: "helloworldapi-service"
  namespace: "default"
  labels:
    app: "helloworldapi"
spec:
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  selector:
    app: "helloworldapi"
  type: "LoadBalancer"
  loadBalancerIP: ""